### ISSUE TITLE
Unauthorized

### ISSUE THREAD

**Issue by prifin** [noto-rious/Nitro.Self-V3#7]
Yo,
When bot tries to snipe the nitro, it always gives this message.
![image](https://user-images.githubusercontent.com/74878234/101267330-b8f9e780-3757-11eb-8773-4896ff8e4048.png)
Whats wrong here?

**Comment by noto-rious** [comment]
This would most likely mean that your main token isn't correct.

**Comment by noto-rious** [comment]
I'm going to close this as I'm pretty sure the problem was addressed. To clarify you can always check the example configuration on the README in the root of the repo. All of the lines containing '//something here' are just example comments that explain things and should not be pasted into your configuration file. 

More-so, addressing Issue#7 in particular I would reflect back to the README's configuration example and make sure your token syntax is correct, and if it is I would further investigate the validity of the token you are supplying. 

If you have any other issues feel free to open an issue.
